.gitignore
CMakeLists.txt
include/OpDefined.hpp
include/Types.hpp
src/Backend.hpp
src/Layer.hpp
src/Tensor.cpp
src/Tensor.hpp
src/backends/cpu/CPUBackend.cpp
src/backends/cpu/CPURoPE.cpp
src/backends/cpu/CPUTensorFunction.hpp
src/backends/cpu/compute/Matmul.cpp
src/models/deepseek/configuration_deepseek.hpp
src/models/deepseek/modeling_deepseek.hpp

- Multi-Head Latent Attention(MLA)  is proposed in [Deepseek-V2](https://arxiv.org/abs/2405.04434)
- MLA is  implemented in the `src/models/deepseek/modeling_deepseek.hpp`

feat: Add  Multi-Head Latent Attention(MLA) support.

---

CMakeLists.txt
examples/demo_imagebind_1mod.cpp
src/Module.hpp
src/ParamLoader.cpp
src/Tensor.hpp
src/models/imagebind/modeling_imagebind.hpp

Add new file `example/demo_imagebind_1mod.cpp`.

feat: Add new demo: demo_imagebind_1mod

---

src/Backend.cpp
src/Backend.hpp
src/Layer.hpp
src/Module.cpp
src/Module.hpp
src/Tensor.cpp
src/Tensor.hpp
src/models/clip/processing_clip.hpp
src/models/fuyu/modeling_fuyu.hpp
src/models/fuyu/processing_fuyu.hpp
src/models/imagebind/processing_imagebind.hpp
src/models/llava/modeling_llava.hpp
src/models/llava/processing_llava.hpp
src/models/vit/processing_vit.hpp
src/tokenizers/Tokenizer.hpp

1. Move `Module::backends` to `Backend::global_backends`
2. Add `Layer::run` which contains `Layer::XIXO_OP`
3. Merge `Tensor::getStaticFuncOps` to `Tensor::getStaticFunc`

refactor:  `Layer::run`  & `Tensor::getStaticFunc`

---

src/Layer.hpp
src/Tensor.cpp
src/backends/cpu/CPUTensorFunction.hpp
src/backends/cpu/compute/Arithmetic.cpp
src/backends/cpu/compute/Arithmetic.hpp

perf:  CPU Function: +-*/

---

.gitignore
CMakeLists.txt
include/OpDefined.hpp
src/Layer.hpp
src/Module.hpp
src/Op.cpp
src/Op.hpp
src/Tensor.cpp
src/Tensor.hpp
src/backends/cpu/CPUBackend.cpp
src/backends/cpu/CPUIRoPE.cpp
src/backends/cpu/CPUIRoPE.hpp
src/backends/cpu/CPULinear.cpp
src/models/phi3/modeling_phi3.hpp

1. feat: add IROPE
2. refactor: `Tensor::run` &`Layer::getFunc`: Tensor -> Tensor&

refactor: `Tensor::run` &`Layer::getFunc`

---

.github/workflows/main.yml
CMakeLists.txt
examples/demo_qwen.cpp
include/Types.hpp
src/Tensor.hpp
src/memory/MemoryPoolManager.cpp
src/memory/SystemMemoryManager.cpp
test/TestSystemMemoryManager.cpp

已通过window的测试：
- MLLM_TEST.exe
- SystemMemoryTest.exe
- memoryPoolTest.exe
- quantize.exe
- demo_qwen.exe

fix 修复windows环境

---

CMakeLists.txt
include/Timing.hpp
src/Layer.hpp
src/backends/cpu/CMakeLists.txt
src/backends/cpu/compute/Matmul.cpp
src/models/clip/processing_clip.hpp
src/models/fuyu/processing_fuyu.hpp
third_party/cmdline.h

1. Pls using Clang15+ to compile mllm project. Notice: U should install Clang15+ from *Visual Studio Installer*!!!
2. The Llvm Tool chain from Visual Studio using MSVC as backend. Pls using Clang with GNU CLI option instead MSVC CLI.
3. The MLLM_TEST has not passed windows compilation right now.
*WARNING!*
The `Timing.hpp` is modified but not tested. chrono(since cpp 11?) is used instead of some system calls.

fix: bug fix for windows compilation

---

.gitignore
src/Tensor.hpp
src/backends/cpu/CMakeLists.txt
src/backends/cpu/compute/SGEMM.cpp
src/backends/cpu/compute/VecDot.hpp
src/models/llava/processing_llava.hpp
src/processor/AudioProcess.cpp
test/CMakeLists.txt
tools/convertor/requirements.txt

Compiled using Clang17. Test Passed

fix: windows compile bug

---

README.md
src/backends/qnn/README.md

Fixed typos.

---

README.md
src/models/fuyu/modeling_fuyu.hpp
src/models/fuyu/processing_fuyu.hpp
src/models/phonelm/configuration_phonelm.hpp
src/models/qwen/tokenization_qwen.hpp
tools/jni/LibHelper.cpp

Add Android Support [PhoneLM-1.5B](https://huggingface.co/collections/mllmTeam/phonelm-672b53c6cb9a8b2f216d7e45).
Android App load images error. Fix [#74 ](https://github.com/UbiquitousLearning/mllm/issues/74)

feat: PhoneLM Instruct Android Demo.

---

include/Types.hpp
src/Layer.hpp
src/Tensor.cpp
src/Tensor.hpp
src/backends/cpu/compute/Matmul.cpp
src/backends/cpu/compute/MatmulElastic.cpp
src/backends/cpu/compute/MatmulSparse.cpp
src/memory/SystemMemoryManager.cpp

Fix  #https://github.com/UbiquitousLearning/mllm/issues/208

fix: free `to` Tensor in Matmul files.

---

CMakeLists.txt
mllm/utils/Dbg.hpp
tests/CMakeLists.txt
tests/utils/CMakeLists.txt
tests/utils/DbgTest.cpp

- Add Windows-specific handling for export symbols
- Implement platform-specific macros for function signature
- Improve argument splitting logic in Dbg macro
- Add support for MSVC compiler
- Update CMakeLists to include new test for Dbg functionality

feat(utils): improve Dbg macro and add Windows support

---

mllm/backends/x86/X86Backend.cpp
mllm/backends/x86/ops/LinearOp.cpp
mllm/backends/x86/ops/LinearOp.hpp
mllm/core/aops/LinearOp.cpp
mllm/core/aops/LinearOp.hpp
mllm/engine/Context.cpp
mllm/engine/SessionTCB.hpp
mllm/mllm.hpp
mllm/mllm.inl
mllm/nn/AbstractNnNode.cpp
mllm/nn/AbstractNnNode.hpp
mllm/nn/Layer.cpp
mllm/nn/Layer.hpp
mllm/nn/Module.cpp
mllm/nn/Module.hpp
mllm/nn/layers/Linear.cpp
mllm/nn/layers/Linear.hpp
tests/nn/CMakeLists.txt
tests/nn/FooNetTest.cpp

feat(x86): add X86 backend support for Linear operation
- Implement X86LinearOp and X86LinearOpFactory for X86 backend
- Update X86Backend to register X86LinearOpFactory
- Modify LinearOpOptions to replace LinearOptions
- Update related files to support new X86 backend functionality

feat(x86): add X86 backend support for Linear operation

---

.gitignore
mllm/backends/x86/CMakeLists.txt
mllm/backends/x86/X86Dispatcher.cpp
mllm/backends/x86/X86Dispatcher.hpp
mllm/backends/x86/ops/LinearOp.cpp
mllm/core/BaseOp.cpp
mllm/core/BaseOp.hpp
mllm/core/Tensor.cpp
mllm/core/aops/LinearOp.cpp
mllm/engine/BuddyMemPool.cpp
mllm/engine/BuddyMemPool.hpp
mllm/engine/Context.cpp
mllm/engine/Context.hpp
mllm/engine/Dispatcher.cpp
mllm/engine/Dispatcher.hpp
mllm/engine/DispatcherManager.cpp
mllm/engine/DispatcherManager.hpp
mllm/engine/MemoryManager.cpp
mllm/engine/MemoryManager.hpp
mllm/engine/Task.cpp
mllm/engine/Task.hpp
mllm/mllm.cpp
mllm/mllm.hpp
mllm/mllm.inl
mllm/nn/Layer.hpp
mllm/nn/Nn.hpp
mllm/utils/Common.hpp
tests/nn/FooNetTest.cpp

- Add X86Dispatcher for CPU task execution
- Implement DispatcherManager for task submission and synchronization
- Update MemoryManager to support buddy memory pool
- Add task creation and execution flow in Context
- Implement simple memory report functionality

feat(core): implement basic task dispatching and memory management

---

mllm/backends/cpu/CPUAllocator.cpp
mllm/backends/cpu/CPUBackend.cpp
mllm/backends/cpu/kernels/Kernels.hpp
mllm/backends/cpu/kernels/x86/fill.cpp
mllm/backends/cpu/kernels/x86/fill.hpp
mllm/backends/cpu/kernels/x86/simd.hpp
mllm/backends/cpu/ops/FillOp.cpp
mllm/backends/cpu/ops/FillOp.hpp
mllm/core/BaseOp.hpp
mllm/core/Tensor.cpp
mllm/core/Tensor.hpp
mllm/core/TensorViewImpl.hpp
mllm/core/aops/FillOp.cpp
mllm/core/aops/FillOp.hpp
mllm/engine/Context.cpp
mllm/engine/Context.hpp
mllm/mllm.inl
mllm/utils/PlatformRTHelper.hpp
tests/utils/PrintTest.cpp

- Add FillOp support for CPU backend
- Implement optimized CPU fill operations for different data types
- Update CPUAllocator to handle FillOp
- Add platform-specific optimizations using SIMD instructions

feat(core): implement FillOp and optimize CPU allocation

---

mllm/compile/ir/GeneratedRTTIKind.hpp
mllm/compile/ir/IRPrinter.hpp
mllm/compile/ir/IRTraceDispatcher.cpp
mllm/compile/ir/IRTraceDispatcher.hpp
mllm/compile/ir/Node.cpp
mllm/compile/ir/Node.hpp
mllm/compile/ir/NodeRTTIClassOfImpl.hpp
mllm/compile/ir/builtin/Interface.hpp
mllm/compile/ir/cf/Op.cpp
mllm/compile/ir/cf/Op.hpp
mllm/compile/ir/graph/Op.cpp
mllm/compile/ir/graph/Op.hpp
mllm/compile/ir/linalg/Op.cpp
mllm/compile/ir/linalg/Op.hpp
mllm/compile/ir/rtti_kind_gen.py
mllm/compile/ir/tensor/Op.cpp
mllm/compile/ir/tensor/Op.hpp
mllm/compile/ir/tensor/Value.cpp
mllm/compile/ir/tensor/Value.hpp
mllm/core/OpTypes.hpp
mllm/core/aops/GraphOps.cpp
mllm/core/aops/GraphOps.hpp
mllm/engine/Dispatcher.hpp

- Add graph IR support for control flow and function calls
- Implement new IR nodes for graph operations
- Update IR printer and node dumping functions
- Add support for new op types in core
- Implement new graph-related ops in core

feat(compile): add graph IR and update related components

---

mllm/compile/PassManager.hpp
mllm/compile/ir/Node.hpp
mllm/compile/passes/Pass.cpp
mllm/compile/passes/Pass.hpp

- Introduce PassManager class to manage and execute optimization passes
- Add Pass class as the base for all optimization passes
- Implement basic pass infrastructure including context management
- Define pass return states for controlling pass execution flow

feat(compile): add pass manager and pass infrastructure

---

mllm/preprocessor/visual/Image.cpp
mllm/preprocessor/visual/Image.hpp

- Implement Image class with functionalities for opening, resizing, and saving images
- Include method to convert image data to Tensor
- Utilize stb_image library for image processing tasks

feat(preprocessor): add Image class for visual data preprocessing

---

mllm/compile/PassManager.cpp
mllm/compile/ir/GeneratedRTTIKind.hpp
mllm/compile/ir/Node.cpp
mllm/compile/ir/Node.hpp
mllm/compile/ir/NodeRTTIClassOfImpl.hpp
mllm/compile/ir/program/Op.cpp
mllm/compile/ir/program/Op.hpp
mllm/compile/ir/rtti_kind_gen.py
mllm/compile/jit/JITRunner.hpp
mllm/compile/passes/Pass.cpp
mllm/compile/passes/Pass.hpp
mllm/compile/passes/Pattern.cpp
mllm/compile/passes/Pattern.hpp
mllm/compile/passes/ProgramLoweringPipeline.cpp
mllm/compile/passes/ProgramLoweringPipeline.hpp
tests/compile/ir/CMakeLists.txt
tests/compile/ir/ProgramLoweringTest.cpp

- Add PassManager to manage and run passes
- Implement Pattern and PatternMatchPass for pattern-based rewriting
- Create ProgramLoweringPipeline to lower different IR levels to program IR
- Add new IR nodes for program representation (JumpOp, LabelOp, EntryPointOp)
- Update IRWriter to support new program IR nodes
- Refactor Node class to use weak pointers for prev/next operations

feat(compile): implement program lowering pipeline

---

.devcontainer/arm/devcontainer.json
.devcontainer/qnn/devcontainer.json
.vscode/extensions.json
.vscode/settings_recommended.json
CMakeLists.txt
README.md
mllm/backends/cpu/CMakeLists.txt
requirements-mini.txt
tasks/build_osx_apple_silicon.yaml

- Add OpenMP support for Apple Clang
- Update CMakeLists.txt for OpenMP configuration
- Create build configuration for Apple Silicon
- Add CMake tools extension to VS Code
- Update README.md with installation instructions

feat(cpu arm backend): add apple silicon support

---

mllm/backends/cpu/CPUBackend.cpp
mllm/backends/cpu/kernels/Kernels.hpp
mllm/backends/cpu/kernels/arm/elementwise.cpp
mllm/backends/cpu/kernels/arm/elementwise.hpp
mllm/backends/cpu/kernels/arm/fill.cpp
mllm/backends/cpu/kernels/arm/fill.hpp
mllm/backends/cpu/kernels/arm/gelu.cpp
mllm/backends/cpu/kernels/arm/gelu.hpp
mllm/backends/cpu/ops/ElewiseOps.cpp
mllm/backends/cpu/ops/ElewiseOps.hpp
mllm/core/Tensor.cpp
mllm/core/aops/ElewiseOps.cpp
mllm/core/aops/ElewiseOps.hpp

- Implement element-wise addition, subtraction, multiplication, division, and negation
- Add corresponding CPU kernels for these operations
- Update Tensor class to support these operations
- Create ElewiseOps.hpp and ElewiseOps.cpp files to define and implement the operations

feat(cpu): add support for element-wise operations

---

.github/ISSUE_TEMPLATE/01-bugs-report.yml
.github/ISSUE_TEMPLATE/02-feature_request.yml
.github/ISSUE_TEMPLATE/03-model-support-request.yml
.github/ISSUE_TEMPLATE/04-performance.yml
.github/ISSUE_TEMPLATE/05-research-experiment.yml
.github/pull_request_template.md
benchmarks/cpu/arm_hpc_sgemm.cpp
docs/contribute/index.rst
docs/contribute/roadmap.rst
docs/quick_start/index.rst
mllm/backends/cpu/kernels/arm/hpc/hpc_sgemm.cpp
mllm/backends/cpu/kernels/arm/hpc/hpc_sgemm.hpp
tests/cpu/HpcArmSgemvKernelTest.hpp
tests/cpu/KernelTest.cpp
tests/cpu/KernelTestHelper.hpp

- Implement optimized matrix multiplication kernels for Arm architecture
- Add support for batched matrix multiplication
- Include new test cases for HPC SGEMV kernels
- Update documentation and roadmap for Arm kernel support

feat(arm): add HPC SGEMV kernel support for MLLM

---

scripts/cuda_core_dump_setenv.sh

- Create cuda_core_dump_setenv.sh to configure CUDA core dump settings
- Set environment variables for enabling and customizing CUDA core dumps
- Include optional setting for containerized environments

feat(scripts): add CUDA core dump setup script

---

mllm/backends/cpu/CPUBackend.cpp
mllm/backends/cpu/ops/SliceOp.cpp
mllm/backends/cpu/ops/SliceOp.hpp
mllm/compile/ir/GeneratedRTTIKind.hpp
mllm/compile/ir/NodeRTTIClassOfImpl.hpp
mllm/compile/ir/linalg/Op.cpp
mllm/compile/ir/linalg/Op.hpp
mllm/compile/ir/rtti_kind_gen.py
mllm/core/OpTypes.hpp
mllm/core/SlicePrimitives.cpp
mllm/core/SlicePrimitives.hpp
mllm/core/Tensor.cpp
mllm/core/Tensor.hpp
mllm/core/aops/SliceOp.cpp
mllm/core/aops/SliceOp.hpp
mllm/nn/lmcache/DynamicCache.cpp
mllm/nn/lmcache/StaticCache.cpp
mllm/nn/lmcache/StaticCache.hpp
tests/nn/CMakeLists.txt
tests/nn/StaticCacheTest.cpp

- Add SliceOp implementation for tensor slicing
- Implement StaticCache class for fixed-size cache
- Update CPUBackend to support SliceOp
- Add tests for StaticCache functionality

feat(core): add support for SliceOp and implement StaticCache

---

CMakeLists.txt
examples/qwen2_vl/main.cpp
mllm/CMakeLists.txt
mllm/backends/cpu/CPUDispatcher.cpp
mllm/engine/Context.cpp
mllm/engine/Context.hpp
mllm/engine/MemoryManager.cpp
mllm/engine/Perf.cpp
mllm/engine/Perf.hpp
mllm/mllm.cpp
mllm/mllm.hpp
tasks/build_osx_apple_silicon_perf.yaml
tests/engine/PerfMemTest.cpp

- Add Perfetto support for detailed performance tracing
- Replace custom perf logic with Perfetto events
- Update CMakeLists to include Perfetto options
- Modify example and test code to use new Perfetto integration
- Remove old perf-related code and structures

feat(perf): integrate Perfetto for performance tracing

---

.github/workflows/docs-deploy.yml

ci(docs): add GitHub Actions workflow for docs deployment
- Create new workflow file for deploying documentation to GitHub Pages
- Set up Python environment and install dependencies
- Build documentation using Sphinx
- Configure and deploy to GitHub Pages on push to v2 branch

ci(docs): add GitHub Actions workflow for docs deployment

---

algorithms/lazy_vlm/models/qwen2_5vl/modeling_qwen2_5vl.hpp
algorithms/lazy_vlm/run.py

- Sort positions to delay computation in next layer for better cache utilization
- Fix position ids prefill logic to ensure correct attention masks
- Enable optimization flags for model compilation
- Adjust causal mask size to accommodate correct attention spans

perf(lazy_vlm): optimize model performance and debugging

---

examples/CMakeLists.txt
examples/llama/CMakeLists.txt
examples/llama/config_tiny_llama.json
examples/llama/demo_tiny_llama.cpp
mllm/models/llama/configuration_llama.hpp
mllm/models/llama/modeling_llama.hpp
mllm/models/llama/tokenization_tiny_llama.hpp

- Implement LLaMAConfig to handle model configuration
- Add LlamaForCausalLM class for LLaMA model
- Implement TinyLlamaTokenizer for tokenization
- Add example demo for LLaMA model usage

feat(models): add LLaMA model support
